on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run greeting action
        uses: tarasowski/greeting@main
        with:
          first_name: 'Anka'
          last_name: 'B.'
